---
# handlers file for haproxy
- name: Restart keepalived
  become: true
  service:
    name: keepalived
    state: restarted

- name: Restart haproxy
  become: true
  service:
    name: haproxy 
    state: restarted