# Префикс для LAN сети
BRIDGE_NET="192.168.56."

DOMAIN="test"

MACHINES = {
  :jenkins => {
    :box_name => "bento/ubuntu-22.04",
    :host_name => "jenkins",  
    :ip_addr => BRIDGE_NET + "111",
    :cpu => 1,
    :ram => 2048, # Megabytes
  },
  :appserver => {
    :box_name => "bento/ubuntu-22.04",
    :host_name => "appserver",  
    :ip_addr => BRIDGE_NET + "112",
    :cpu => 1,
    :ram => 2048
  }
}

Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|                   # Проходим по элементах массива "servers"
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]               # Поднять машину из образа
            box.vm.host_name = boxconfig[:host_name]        # Hostname который будет присвоен VM (самой ОС)
            box.vm.usable_port_range = (2200..2250)         # Пул портов, который будет использоваться для подключения к каждый VM через 127.0.0.1
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                vb.name = boxconfig[:host_name]     # Можно перезаписать название VM в Vbox GUI
                vb.cpus = boxconfig[:cpu]
                vb.memory = boxconfig[:ram]
            end
            # Выполнение настроечных скриптов в ОС
            # SHELL
            box.vm.provision "shell", path: "scripts/jenkins.sh"
            box.vm.provision "shell", path: "scripts/postgres.sh"
        end
    end
end
