apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  # WARNING: It is _strongly_ recommended that you keep this the default
  # (127.0.0.1) for security reasons. However it is possible to change this.
  apiServerAddress: "$DOCKER_HOST_IP"
  # By default the API server listens on a random open port.
  # You may choose a specific port but probably don't need to in most cases.
  # Using a random port makes it easier to spin up multiple clusters.
  apiServerPort: 6443
  disableDefaultCNI: true
  podSubnet: "$POD_SUBNET"
  serviceSubnet: "$SERVICE_SUBNET"
nodes:
- role: control-plane
  # kubeadmConfigPatches:
  # - |
  #   kind: InitConfiguration
  #   nodeRegistration:
  #     kubeletExtraArgs:
  #       node-labels: "ingress-ready=true"
  # extraPortMappings:
  # - containerPort: 80
  #   hostPort: 80
  #   protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "nodePort=true"
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 30100
    hostPort: 30100
    # listenAddress: "127.0.0.1" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 80
    hostPort: 80
    protocol: TCP
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "nodePort=true"
  extraPortMappings:
  - containerPort: 30200
    hostPort: 30200
    protocol: TCP
