- name: Zookeeper | Install
  become: true
  block:

  - name: Zookeeper | Create dir for dowload tarball
    file:
      path: '{{ zookeeper_tarball_dir }}'
      state: directory
      owner: '{{ zookeeper.user }}'
      group: '{{ zookeeper.group }}'

  - name: Zookeeper | Download zookeeper tarball
    get_url:
      url: '{{ zookeeper_download_url }}'
      dest: '{{ zookeeper_tarball_dir }}'
      validate_certs: no
    register: result
    until: result is succeeded
    retries: 10
    delay: 2

  - name: Zookeeper | Create bin directory
    file:
      path: '{{ zookeeper_bin_dir }}'
      state: directory
      owner: '{{ zookeeper.user }}'
      group: '{{ zookeeper.group }}'

  - name: Zookeeper | Creates symlink
    file:
      src: '{{ zookeeper_bin_dir }}'
      dest: '{{ zookeeper_bin_dir_symlink }}'
      state: link
      owner: '{{ zookeeper.user }}'
      group: '{{ zookeeper.group }}'
    when:
      - zookeeper_bin_dir_symlink != zookeeper_bin_dir

  - name: Zookeeper | Unpack tarball
    unarchive:
      remote_src: true
      src: '{{ zookeeper_tarball_dir }}/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz'
      dest: '{{ zookeeper_bin_dir }}'
      extra_opts: '--strip-components=1'
      creates: '{{ zookeeper_bin_dir }}/conf'
      owner: '{{ zookeeper.user }}'
      group: '{{ zookeeper.group }}'

  - name: Zookeeper | Create zookeeper data directories
    file:
      path: '{{ item.data_dir }}'
      state: directory
      owner: '{{ zookeeper.user}}'
      group: '{{ zookeeper.group }}'
    loop: '{{ zookeeper_instances }}'

  - name: Zookeeper | Create zookeeper log directories
    file:
      path: '{{ item.log_dir }}'
      state: directory
      owner: '{{ zookeeper.user}}'
      group: '{{ zookeeper.group }}'
    loop: '{{ zookeeper_instances }}'